# Fichier de configuration ansible pour la machine VM1

- hosts: localhost
  remote_user: root
  tasks:

# Configurations Réseaux
  - name: Suppression de la passerelle par défaut
    shell: ip route del default
    ignore_errors: true

  - name: Configuration de VM1/eth1
    nmcli:
      type: ethernet
      conn_name: eth1 via ansible
      ifname: eth1
      state: present
      autoconnect: true
      ip4: 172.16.2.131/28

  - name: Configuration de la route vers LAN2 via VM2
    community.general.nmcli:
      type: ethernet
      conn_name: eth1 via ansible
      ifname: eth1
      routes4: 172.16.2.160/28 172.16.2.132
      state: present

  - name: Activation explicite de la configuration eth1
    shell: nmcli con up "eth1 via ansible"

  - name: Configuration de VM1/eth2
    nmcli:
      type: ethernet
      conn_name: eth2 via ansible
      ifname: eth2
      state: present
      autoconnect: true
      ip6: fc00:1234:3::1/64

  - name: Activation explicite de la configuration eth2
    shell: nmcli con up "eth2 via ansible"
