# Fichier de configuration ansible pour la machine VM2

- hosts: localhost
  remote_user: root
  tasks:

# Configurations Réseaux
  - name: Suppression de la passerelle par défaut
    shell: ip route del default
    ignore_errors: true

  - name: Configuration de VM2/eth1
    nmcli:
      type: ethernet
      conn_name: eth1 via ansible
      ifname: eth1
      state: present
      autoconnect: true
      ip4: 172.16.2.132/28

  - name: Activation explicite de la configuration eth1
    shell: nmcli con up "eth1 via ansible"

  - name: Configuration de VM2/eth2
    nmcli:
      type: ethernet
      conn_name: eth2 via ansible
      ifname: eth2
      state: present
      autoconnect: true
      ip4: 172.16.2.162/28

  - name: Activation explicite de la configuration eth2
    shell: nmcli con up "eth2 via ansible"

  - name: Activation du routage IPv4
    sysctl:
      name: net.ipv4.ip_forward
      value: '1'
      sysctl_set: yes
